### PR TITLE
Cleanup gitignore.

### LINKED ISSUE #34: Review `.gitignore` file
The mch-python-blueprint has a `.gitignore` file, it would be good to go through and see which parts of the `.gitignore` are relevant in the updated blueprint.

### PR DESCRIPTION
**Pull request by bascrezee**
I cleaned up the `.gitignore` file, there was lots of rubbish related to linters or IDEs etc. I tested the new `.gitignore` for both the blueprint itself, and a package created from the blueprint. 

Closes #34

### CODE REVIEW

**Comment by ruestefa** [comment]
Could/should there be a github actions test that checks that `git status` is empty after running tests, linters etc.?

**Comment by ruestefa** [comment]
At the very least, everything that's produced by tools provided by the blueprint should be properly ignored and not left to the user, and that could be ensured by checking `git status` at the end of the respective github action plans. That's all I'm proposing.

Ignoring things produced by other tools can be left to the users, sure. (Although I'd personally still opt for including ignores of quasi-standard files like common editors, which is why I'm a bit puzzled why you'd remove the vscode settings file given most of you use vscode -- unless the plan is to have project-specific settings files in the repos).

**Comment by bascrezee** [comment]
I think we have a bit a different philosophy. I like to reduce complexity and therefore really provide a very minimal `.gitignore` listing only files that a user for sure will have to deal with and for sure does not want to have committed. If a `.vscode` would pop up in my directories, I would notice, and then add it manually to the `.gitignore`, like this a user keeps full control over what happens, instead of just using what is provided. One could also argue that IDE configs should be listed in `.git/info/exclude`, see [here](https://softwareengineering.stackexchange.com/a/367594). But this really is a matter of taste. Other opinions are welcome. @clairemerker ?

**Comment by ruestefa** [comment]
> I like to reduce complexity and therefore really provide a very minimal .gitignore listing only files that a user for sure will have to deal with

OK, good point, you've convinced me regarding my 2nd remark. :)

The first remark (check in actions) however refers exactly to "files that a user for sure will have to deal with" with a blueprint-based project and therefore still stands. I could try to implement such a simple test if you agree that this would be useful.

**Comment by clairemerker** [comment]
I think I agree with both of you regarding:
>  I like to reduce complexity and therefore really provide a very minimal .gitignore listing only files that a user for sure will have to deal with
Regarding the second point, I am not yet really sure about the implications. What use case do you want to catch with the Actions?

**Comment by ruestefa** [comment]
> Regarding the second point, I am not yet really sure about the implications. What use case do you want to catch with the Actions?

Say a new linter is added, or an existing linter changes the name of a temporary file or directory, and this is not covered by `.gitignore` and might therefore be committed accidentally. A simple automated check would ensure that this would be captured right away. Not the most critical issue, for sure, but should also neither be hard to implement/maintain nor expensive to run.

**Comment by bascrezee** [comment]
> > Regarding the second point, I am not yet really sure about the implications. What use case do you want to catch with the Actions?
> 
> Say a new linter is added that uses a local cache, or an existing linter changes the name of a temporary file or directory, and this is not covered by `.gitignore` and might therefore be committed accidentally. 

In my opinion this is the responsibility of the blueprint user, to not commit files that should not be committed. 


> A simple automated check would ensure that this would be captured right away. Not the most critical issue, for sure, but should also neither be hard to implement/maintain nor expensive to run.
Yes, I agree about maintenance, but I am more worried that this single line is not understandable by someone looking at the code. I think everything that is done in the blueprint should be easy to understand. But again, this probably is a matter of taste.

**Comment by ruestefa** [comment]
> In my opinion this is the responsibility of the blueprint user, to not commit files that should not be committed.

> I am more worried that this single line is not understandable by someone looking at the code

I think we're not talking about the same thing. What I have in mind purely concerns the blueprint itself and would thus not be exposed to the users. It's a safety net for the blueprint devs to ensure that new projects are not broken.

Anyway, I've gone ahead and just implemented it (#104), and it was worth it as the check initially failed b/c of an unignored `build/` directory after install, which I've thus added to `.gitignore`.

_PS: Not to argue against the decision to go with a bare-bones `.gitignore`, but it might be worth noting that the long version inherited from the upstream blueprint is (as far as I can tell) based on the official [github template](https://github.com/github/gitignore), i.e., not just some custom collection of ignores collected by some random person. Maybe a link to that template could be added to the docs in case a blueprint-based project prefers a comprehensive over a bare-bones approach._

**Comment by bascrezee** [comment]
> > In my opinion this is the responsibility of the blueprint user, to not commit files that should not be committed.
> 
> > I am more worried that this single line is not understandable by someone looking at the code
> 
> I think we're not talking about the same thing. What I have in mind purely concerns the blueprint itself and would thus not be exposed to the users. It's a safety net for the blueprint devs to ensure that new projects are not broken.

I think both the blueprint itself and the projects created from it should be easy to understand. I really don't see the need for that additional check, as one would find out anyways, also without the check. Personally, I learn a lot from your suggestions (`git status --porcelain` --> cool stuff! ). But if my 'wish' of having a very bare `.gitignore` has the consequence that the MCH python blueprint gets more complicated, then I am reaching the opposite of what I wanted, and I would consider closing #101 . 


> 
> Anyway, I've gone ahead and just implemented it (#104), and it was worth it as the check initially failed b/c of an unignored `build/` directory after install, which I've thus added to `.gitignore`.

Good test of the check, but manually you would find out the same, right?


> 
> _PS: Not to argue against the decision to go with a bare-bones `.gitignore`, but it might be worth noting that the long version inherited from the upstream blueprint is (as far as I can tell) based on the official [github template](https://github.com/github/gitignore), i.e., not just some custom collection of ignores collected by some random person. Maybe a link to that template could be added to the docs in case a blueprint-based project prefers a comprehensive over a bare-bones approach._

That is good to know, I feel better now about just using that one, compared to a very bare one. It would be good to have more opinions, because now it's just us. @clairemerker  ? A very bare `.gitignore` or list a bunch of files (a GH template?) that are potentially created by future blueprint projects?

**Comment by ruestefa** [comment]
> Good test of the check, but manually you would find out the same, right?

Well, yes, but finding issues automatically is the whole point of github actions, isn't it?

**Comment by clairemerker** [comment]
To be honest I feel quite unopinionated on this one... Also, I am maybe not the best person to ask because I work a lot with cluttered `git status` and I don't really care :D But here is what I think:
- I like the idea of a mostly clean `.gitignore`, at least in the created packages
- and I also like the idea of the GitHub Action check _in the blueprint itself_ because I feel that it should be a requirement for developers of the blueprint to provide a clean `git status` when a package is newly generated. And this will help us to stick to this requirement. I looked at the changes to the workflow file and I think it is not too complicated to be included.

But this is more my gut feeling than an informed opinion...

**Comment by cosunae** [comment]
launch jenkins

**Review by twicki — APPROVED** [review]
LGTM

**Pull request merged**
