### PR TITLE
Bundle tools scripts

### PR DESCRIPTION
**Pull request by ruestefa**
- Group bash scripts into `tool/` subdirectory.
- Add `tools/` to root of blueprint with two bash scripts to update `environment.yml` and `tmpl/environment.yml.j2`, respectively.
  - Feel free not to merge these scripts to avoid additional custom code, but at least they are not exposed to blueprint users and thus less critical in terms of maintenance than those in `tmpl/tools/`.

Based on branch `unify-reqs` (#87).

### CODE REVIEW

**Review by regDaniel — CHANGES_REQUESTED** [review]
I agree to have the two additional scripts in the blueprint repo as this is complexity which is never exposed to the users. Also, bundling the scripts seems like a reasonable idea to me. But I need to clarify with @clairemerker first and properly test the scripts. I'll approve once this is done.

**Review by regDaniel — APPROVED** [review]

**Comment by regDaniel** [comment]
> I agree to have the two additional scripts in the blueprint repo as this is complexity which is never exposed to the users. Also, bundling the scripts seems like a reasonable idea to me. But I need to clarify with @clairemerker first and properly test the scripts. I'll approve once this is done.

we discussed it and both think it's reasonable. We'd even go as far as automatizing this task with a cron job, see #95

**Comment by regDaniel** [comment]
launch jenkins

**Comment by ruestefa** [comment]
launch jenkins

**Comment by ruestefa** [comment]
hand-merged due to conflicts

**Pull request merged**
