### PR TITLE
cleanup

### PR DESCRIPTION
**Pull request by twicki**
## Purpose
Minor cleanup

## Code Changes
- README.md:
  - formatting
- copier.yaml
  - change the default year to current

### CODE REVIEW

**Comment by cosunae** [comment]
Thanks @twicki 
can you describe how to reproduce the bug you encountered ? Particularly why it was not triggered by the github actions/jenkins, and whether we need to extend the tests

**Comment by twicki** [comment]
The pre-commit hook on the blueprint repo is not the same as the one running on the generated packages. The only way I found to test the used blueprint is on [here](https://github.com/MeteoSwiss-APN/testlatestblueprint). If we wanted to be thorough I think we need a plan that does all the steps in setting up a project from the blueprint and test this one on a regular basis - which is not what the github actions here do. 

As for reproducing it:
```
copier git@github.com:MeteoSwiss-APN/mch-python-blueprint.git demo
cd demo
./setup_env.sh -u -e -n demo
pip install --editable .
conda activate demo
conda upadte requirements/requirements.yml
pre-commit run --all-files
```

**Comment by ruestefa** [comment]
> `conda install pre-commit`

That's already done in `./setup_env.sh -u -e -n demo` (`pre-commit` is in `requirements.yml`).

**Comment by twicki** [comment]
no, pre-commit is not in requirements, it is only in dev-requirement

**Comment by ruestefa** [comment]
> no, pre-commit is not in requirements, it is only in dev-requirement

`dev-requirements.yml` has recently been merged into `requirements.yml` (b/c of the problems w/ `conda env` not keeping track of previously imposed version constraints), so you must be working on an oudated branch.

**Pull request closed without merging**
